### ISSUE TITLE
Issuer should be appended to the query parameter

### ISSUE THREAD

**Issue by calvn** [Daplie/browser-authenticator#1]
Right now the fields generates a url and the QR code like such:
`otpauth://totp/ISSUER:user@domain.com?secret=FOO`

The issuer should also be included in the query parameter so that Google Authenticator app sets the label correctly:
`otpauth://totp/ISSUER:user@domain.com?secret=FOO&issuer=ISSUER`

**Comment by coolaj86** [comment]
It does:

https://github.com/Daplie/browser-authenticator/blob/gh-pages/authenticator.js#L90

Can you give an example of why you think that it doesn't?

It could be that the QR generator that you're using is omitting it to save space.

**Comment by calvn** [comment]
I am using Google Authenticator. On https://daplie.github.io/browser-authenticator/ the issuer does not appear as a query parameter on the URI result.
<img width="671" alt="screen shot 2016-09-02 at 1 31 40 pm" src="https://cloud.githubusercontent.com/assets/1883212/18212528/b48f068c-7111-11e6-9e84-1571caf26c52.png">

**Comment by coolaj86** [comment]
That was just the demo, not the library, but now you have it there too.

:)

**Comment by calvn** [comment]
Cool, I was using the UI to generate the QR code directly :) Closing since it's there now.
