### ISSUE TITLE
Specifying other fields, like Digits

### ISSUE THREAD

**Issue by p1r473** [Daplie/browser-authenticator#2]
Any way to add a text box to customize some other fields, such as digits?
Thanks

**Comment by coolaj86** [comment]
I don't understand your question.

What part of the code or the demo are you referring to?

Can you show me a screenshot or sample code?

**Comment by p1r473** [comment]
In this example

otpauth://totp/aa@REALM.COM:a?digits=8&secret=UPHKK3ZNH2DMC52Q

Digits = 8 is specified. Not the standard 6
